@base = http://192.168.1.114:10001

#### GET
GET {{base}}/clientes

#### GET
GET {{base}}/clientes/64c18dd5f2d3c593c04408ee

#### GET
GET {{base}}/clientes/64c18dd5f2d3c593c04408e4

#### POST
POST {{base}}/clientes
Content-Type: application/json

{
    "nombre": "Kathleen",
    "apellido" : "Sta Teresa",
    "empresa": "Facebook",
    "email": "miyudanger20@gmail.com",
    "telefono":"2222221"
}

#### PUT
PUT {{base}}/clientes/64c18dd5f2d3c593c04408ee
Content-Type: application/json

{
    "nombre": "Arturo",
    "apellido": "Cardoso",
    "empresa": "Netflix",
    "email": "acardoso@gmail.com",
    "telefono": "923238681"
}

#### DELETE
DELETE {{base}}/clientes/64c18deaf2d3c593c04408f0