@base = http://localhost:5000

#### GET
GET {{base}}/productos

#### GET
GET {{base}}/productos/64c197a234eeb152402ed00d

#### GET
GET {{base}}/productos/64c18dd5f2d3c593c04408e8

#### POST
POST {{base}}/productos
Content-Type: multipart/form-data; boundary=boundary123

{
    "nombre": "Camisa VueJs",
    "precio" : 15000,
    "imagen" : 
}



#### PUT
PUT {{base}}/productos/64c197a234eeb152402ed00d
Content-Type: application/json

{
    "nombre": "Lapiz BIC",
    "precio" : 1500
}

#### DELETE
DELETE {{base}}/productos/64c265c5fe9904e8874889a6